name: flutterapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  image_picker: ^0.6.2+2
  firebase_storage:
  http: ^0.12.0+4
  font_awesome_flutter: ^8.5.0
  js_shims: ^1.0.0
  charts_flutter: ^0.8.1
  pdf: ^1.6.0
  fluttertoast: ^3.1.3
  email_validator: ^1.0.0
  pull_to_refresh: ^1.5.8
  settings_ui: ^0.2.0
  url_launcher: ^3.0.0
  google_maps_flutter: ^0.5.11+1
  flutter_polyline_points: ^0.1.0
  progress_dialog: ^1.2.1
  shared_preferences: ^0.5.6+3
  location: ^3.0.0
  table_calendar: ^2.2.3
  path_provider:
  network_image_to_byte: ^0.0.1
  introduction_screen: ^1.0.7
  awesome_loader: ^0.0.3
  local_auth: ^0.6.2+2
  material_design_icons_flutter:
  localize_and_translate:
  google_maps_utils: ^1.2.0+3
  maps_toolkit: ^1.0.1+3
  flutter_slidable: "^0.4.7"
  unicorndial: ^1.1.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_offline: 0.2.4+1
  youtube_player_flutter: ^6.1.0+4
  # dynamic_theme: ^1.0.0

  provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_localizations: ^0.17.10
# dependency_overrides:
#   flutter_offline: 0.2.4+1
#   connectivity: ^0.4.3+6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/logotwo.png
    - assets/images/logoone.jpg
    - assets/images/title.jpg
    - assets/images/signIn.png
    - assets/images/hospital.png
    - assets/images/profile.png
    - assets/images/nearestLocation.png
    - assets/images/result.png
    - assets/images/schedule.png
    - assets/images/treatmentplan.png
    - assets/langs/en.json
    - assets/langs/ar.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Iconmed
      fonts:
        - asset: fonts/Iconmed.ttf
  # To add assets to your application, add an assets section, like this:
  # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
